# Learnings

In [23]:
import numpy as np
import pandas as pd

## Who knew these methods existed!

In [42]:
a = np.arange(4)
print(a)
np.add.accumulate(np.arange(4))

[0 1 2 3]


array([0, 1, 3, 6])

In [41]:
np.add.reduce(np.arange(4))

6

In [38]:
np.sum(np.arange(4))

6

In [5]:
a = np.random.randint(10, size=(3, 3))
a

array([[1, 1, 1],
       [6, 6, 2],
       [7, 9, 0]])

In [7]:
b = np.empty_like(a)
b

array([[-6917529027641081856,  6917537815407072623,                    5],
       [                   0,                    0,                    0],
       [-6917529027641081856,  3458773301586529315, -6917529027641081854]])

In [9]:
np.power(2, a, out=b)
b

array([[  2,   2,   2],
       [ 64,  64,   4],
       [128, 512,   1]])

In [15]:
x = np.arange(3).reshape(1, -1)
y = np.arange(3).reshape(-1, 1)

print(x)
print(y)
x + y

[[0 1 2]]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [22]:
a = np.linspace(0, 4, 5)
a[2] = np.nan

print(a)
print(np.cumsum(a))
np.nancumsum(a)

[ 0.  1. nan  3.  4.]
[ 0.  1. nan nan nan]


array([0., 1., 1., 4., 8.])

In [24]:
?pd.IndexSlice

Type:        _IndexSlice
String form: <pandas.core.indexing._IndexSlice object at 0x116b26518>
File:        ~/venv/lib/python3.6/site-packages/pandas/core/indexing.py
Docstring:  
Create an object to more easily perform multi-index slicing

Examples
--------

>>> midx = pd.MultiIndex.from_product([['A0','A1'], ['B0','B1','B2','B3']])
>>> columns = ['foo', 'bar']
>>> dfmi = pd.DataFrame(np.arange(16).reshape((len(midx), len(columns))),
                        index=midx, columns=columns)

Using the default slice command:

>>> dfmi.loc[(slice(None), slice('B0', 'B1')), :]
           foo  bar
    A0 B0    0    1
       B1    2    3
    A1 B0    8    9
       B1   10   11

Using the IndexSlice class for a more intuitive command:

>>> idx = pd.IndexSlice
>>> dfmi.loc[idx[:, 'B0':'B1'], :]
           foo  bar
    A0 B0    0    1
       B1    2    3
    A1 B0    8    9
       B1   10   11


In [29]:
nrows, ncols = 100000, 3
rng = np.random.RandomState(42)
df1, df2, df3, df4 = (pd.DataFrame(rng.rand(nrows, ncols))
                      for i in range(4))

# Eval is faster
pd.eval('-df1 * df2 / (df3 + df4)');

In [32]:
df = pd.DataFrame(rng.rand(5, 3), columns=['A', 'B', 'C'])
df.eval('D = (A + B) / C', inplace=True)
df.head()

A         B         C          D
0  0.060142  0.217764  0.029372   9.461580
1  0.251282  0.883146  0.764247   1.484373
2  0.990463  0.151528  0.631808   1.807498
3  0.070641  0.951394  0.075030  13.621750
4  0.098904  0.744702  0.169776   4.968946

In [33]:
df.query('A < 0.5 and B < 0.5')

A         B         C        D
0  0.060142  0.217764  0.029372  9.46158